### ISSUE TITLE
Title bar customization

### ISSUE THREAD

**Issue by Ypot** [protesilaos/logos#10]
Hi

Could it be possible to hide or change colors of the emacs title bar?
It has very bright colors, that make difficult to read in the night.

Best regards!

**Comment by Ypot** [comment]
Solved, using "F11" on Windows, for a full screen frame.

**Comment by protesilaos** [comment]
Hello @Ypot!  I am not sure which colours you are referring to.  Is `logos` involved in this process?  Maybe we can do something about it, though I am not familiar with what you are referring to.
