### ISSUE TITLE
How could be menu and tool bars hidden?

### ISSUE THREAD

**Issue by Ypot** [protesilaos/logos#2]
Hi!
I keep using logos-focus-mode, it's great.
Today I was trying to hide menu bar, and toolbar. When I launch logos, they disappear but immediately they appear again.

`(logos-focus-mode-extra-functions '(adaptive-wrap-prefix-mode menu-bar-mode tool-bar-mode))`

**Comment by protesilaos** [comment]
Hello @Ypot!

Does this work for you?

```elisp
;; Assuming the `menu-bar-mode' is enabled by default...
(defun my-logos-hide-menu-bar ()
  (logos--mode 'menu-bar-mode -1))

(add-hook 'logos-focus-mode-extra-functions #'my-logos-hide-menu-bar)

;; Assuming the `tool-bar-mode' is enabled by default...
(defun my-logos-hide-tool-bar ()
  (logos--mode 'tool-bar-mode -1))

(add-hook 'logos-focus-mode-extra-functions #'my-logos-hide-tool-bar)
```

**Comment by Ypot** [comment]
> Hello @Ypot!
> 
> Does this work for you?

I'd say so. Do you like it? ;D
![logos-focus-mode](https://user-images.githubusercontent.com/30699014/185700605-111c066c-9b0c-4864-9f35-8c7a86d35386.gif)

**Comment by protesilaos** [comment]
Very well!  I added this to the manual as well.
