### ISSUE TITLE
Reading in the lower half of the screen

### ISSUE THREAD

**Issue by Ypot** [protesilaos/logos#5]
Hi Prot.
Reading your last change log, makes irresistible to ask you about this.

- Wish: to read always in the lower half of the window. So my eyes always look downward, and it's more comfortable.
- Wanted solution: a key combination that scrolls half window and positions the cursor in the middle of the window, like `C-l` does. Now we could use the new logos-keymap, I suppose.
- Kaotic trial in progress:

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; (defun scroll-half-window-ahead ()		     ;;		  ;;
;;   "Scroll ahead half window"			     ;;		  ;;
;;   (interactive)				     ;;		  ;;
;; (scroll-up-command (/(count-screen-lines) 2))     		  ;;
;;   (move-to-window-line nil))			     		  ;;
;; (global-set-key "\C-v" 'scroll-half-window-ahead) ;;		  ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

Note: If you prefer to use the mail list, or other way for this kind of suggestions, let me know, I will adapt myself.

**Comment by protesilaos** [comment]
Hello @Ypot!

> Wish: to read always in the lower half of the window. So my eyes always look downward, and it's more comfortable.

I am not sure I understand exactly how you imagine it.  Do you mean that you have 1 window open and when you enable `logos-focus-mode` it keeps the cursor in the lower part of the screen?

> Wanted solution: a key combination that scrolls half window and positions the cursor in the middle of the window, like `C-l` does. Now we could use the new logos-keymap, I suppose.

Have you tried either `scroll-lock-mode` or `logos-scroll-lock`?  If you do `C-l` to centre the cursor and then enable `logos-focus-mode` with scrolling locked, the focused line will stay in the centre.

* * *

I suggest you set `logos-scroll-lock` to `t` and then try this after activating `logos-focus-mode` (assuming I understood your idea):

```elisp
(defun my-logos-lower-third-scroll ()
  "Keep the cursor in the lower third of the window."
  (interactive)
  ;; You can change the `3` to whatever fraction works for you.
  (let ((height (truncate (window-height) 3)))
    (move-to-window-line (- height))))
```

Add this command to `logos-focus-mode-map`.

**Comment by Ypot** [comment]
Thanks, Prot. Effectively, I think I didn't express myself at all.

I will share a video where the cursor will show the lines I want to read, but it shouldn't be necessary to move the cursor to get this effect:

https://www.tiktok.com/@yporg/video/7138339295701650694?is_from_webapp=1&sender_device=pc&web_id=7100507416085399046

I would like to scroll the window like that, but without needing to move the cursor manually. 

Evaluating a function scroll-half-window-ahead: 
- Window would scroll like you see in the video: half window.
- The cursor would go to the middle of the window, each time the function is evaluated
- All that should happen without being needed to move the cursor manually.

**Comment by protesilaos** [comment]
Maybe this, then?  I bind it to the Down arrow, but you can use something different:

```elisp
(defun my-logos-half-page-scroll ()
  "Keep the cursor centered and scroll half window down."
  (interactive)
  ;; You can change the `3` to whatever fraction works for you.
  (let ((height (truncate (window-height) 2)))
    (forward-line height)
    (recenter nil)))

(define-key logos-focus-mode-map (kbd "<down>") #'my-logos-half-page-scroll)
```

**Comment by Ypot** [comment]
I think I got it (or almost):

```
 (defun my-logos-half-page-scroll ()
    "Keep the cursor centered and scroll half window down."
    (interactive)
    (move-to-window-line -1)
    (recenter))
(define-key logos-focus-mode-map (kbd "C-v") #'my-logos-half-page-scroll)
```

**Comment by protesilaos** [comment]
I can't decide which of your two suggestions is better for you.  I would personally prefer the latter, as the recentring throws me off and disorients me.

**Comment by Ypot** [comment]
Thanks for your help, I couldn't have done it by myself. I will keep this, by now:

```emacs-lisp
   (defun my-logos-half-page-scroll ()
     "Keep the cursor centered and scroll half window down."
     (interactive)
     (move-to-window-line -1)
     (next-line 2))

```

**Comment by protesilaos** [comment]
You are welcome!  It looks good.
