### ISSUE TITLE
Hyphenation

### ISSUE THREAD

**Issue by Ypot** [protesilaos/logos#7]
Could it be possible to enable word hyphenation in logos-focus-mode?
I can't find information about hyphenation in the guide. 

Hyphenated text:

> Lorem ipsum do-
> lor sit amet, con-
> sectetur adipiscing
> elit. 

Wrapped text:

> Lorem ipsum 
> dolor sit amet, 
> consectetur 
> adipiscing elit.

**Comment by protesilaos** [comment]
Does Emacs support such a feature?  If yes, then it's just a matter of integrating with with `logos-focus-mode`.

**Comment by Ypot** [comment]
After learning about hyphenation, margins, visual-line, truncate-lines, etc., I think emacs doesn't have rules to hyphenate words correctly. 
So, I am discarding this feature. For something similar, probably it would be necessary to export to LaTeX, but that wouldn't be org-mode editor.
